# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

formats: []
# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - method: pip
      path: ./docs
    - requirements: docs/requirements.txt
    - requirements: requirements.txt
      extra_requirements:
        - docs
    - method: setuptools
      path: jockmkt_trading_bot/jockbot

        # Build documentation in the docs_sdk/ directory with Sphinx
sphinx:
   configuration: docs/conf.py
   builder: html

# If using Sphinx, optionally build your docs_sdk in additional formats such as PDF
# formats:
#    - pdf

# Optionally declare the Python requirements required to build your docs
# python:
#   install:
#   - requirements: docs/requirements.txt
