[build-system]
requires = ['jockmkt-sdk']
build-backend = "setuptools.build_meta"

[project]
name = "jockbot"
authors = [{name = "Alex Friedman/nysugfx", email = "nysu.gfx@gmail.com"}]
dynamic = ["version", "description"]
