[build-system]
requires = ["DateTime >= 4.3", "setuptools>=65", "typing >= 3.7.4"]
build-backend = "setuptools.build_meta"

[project]
name = "jockbot"
authors = [{name = "Alex Friedman/nysugfx", email = "nysu.gfx@gmail.com"}]
dynamic = ["version", "description"]
