[build-system]
requires = ["requests >= 2.27.1", "DateTime >= 4.3", 'jockmkt-sdk >= 0.2.14']

[project]
name = "jockbot"
authors = [{name = "Alex Friedman/nysugfx", email = "nysu.gfx@gmail.com"}]
dynamic = ["version", "description"]
